"""技能池管理服务"""

import json
import logging
from datetime import datetime, timezone

import aiosqlite

logger = logging.getLogger(__name__)


class SkillService:
    """技能池 CRUD + 过滤 + 岗位等级匹配"""

    # ---- helpers ----

    @staticmethod
    def _row_to_dict(row: aiosqlite.Row) -> dict:
        """Convert an aiosqlite.Row to a plain dict."""
        return dict(row)

    @staticmethod
    def _strip_tools(skill: dict) -> dict:
        """Remove tools_json (internal implementation detail, not user-visible)."""
        skill.pop("tools_json", None)
        return skill

    # ---- list / get ----

    async def list_skills(
        self,
        db: aiosqlite.Connection,
        *,
        category: str | None = None,
        complexity: str | None = None,
        position_id: str | None = None,
        min_level: str | None = None,
        is_preset: bool | None = None,
        is_active: bool | None = None,
    ) -> list[dict]:
        """获取技能列表，支持多维度过滤"""

        clauses: list[str] = []
        params: list[object] = []

        if category is not None:
            clauses.append("category = ?")
            params.append(category)

        if complexity is not None:
            clauses.append("complexity = ?")
            params.append(complexity)

        if is_preset is not None:
            clauses.append("is_preset = ?")
            params.append(int(is_preset))

        if is_active is not None:
            clauses.append("is_active = ?")
            params.append(int(is_active))

        if min_level is not None:
            clauses.append("applicable_min_level = ?")
            params.append(min_level)

        where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
        sql = f"SELECT * FROM skills{where} ORDER BY created_at DESC"

        async with db.execute(sql, params) as cursor:
            rows = await cursor.fetchall()

        skills = [self._strip_tools(self._row_to_dict(r)) for r in rows]

        # position_id 过滤需要在 Python 层检查 JSON 字段
        if position_id is not None:
            filtered: list[dict] = []
            for s in skills:
                applicable = json.loads(s.get("applicable_positions") or "[]")
                if position_id in applicable:
                    filtered.append(s)
            skills = filtered

        return skills

    async def get_skill(self, db: aiosqlite.Connection, skill_id: str) -> dict | None:
        """获取单个技能详情"""
        async with db.execute("SELECT * FROM skills WHERE id = ?", (skill_id,)) as cur:
            row = await cur.fetchone()
        if row is None:
            return None
        return self._strip_tools(self._row_to_dict(row))

    # ---- create ----

    async def create_skill(self, db: aiosqlite.Connection, data: dict) -> dict:
        """创建自定义技能"""
        now = datetime.now(timezone.utc).isoformat()
        # applicable_positions 存储为 JSON 字符串
        applicable_positions = data.get("applicable_positions")
        if applicable_positions is not None and isinstance(applicable_positions, list):
            applicable_positions = json.dumps(applicable_positions)

        opencode_tools = data.get("opencode_tools")
        if opencode_tools is not None and isinstance(opencode_tools, list):
            opencode_tools = json.dumps(opencode_tools)

        mcp_ids = data.get("mcp_ids")
        if mcp_ids is not None and isinstance(mcp_ids, list):
            mcp_ids = json.dumps(mcp_ids)

        sql = """
            INSERT INTO skills (name, description, category, complexity,
                                recommended_model_tier,
                                applicable_positions, applicable_min_level,
                                instructions, opencode_tools, mcp_ids,
                                version, is_preset, is_active, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 0, 1, ?, ?)
        """
        params = (
            data["name"],
            data.get("description"),
            data["category"],
            data["complexity"],
            data["recommended_model_tier"],
            applicable_positions,
            data.get("applicable_min_level", "junior"),
            data.get("instructions"),
            opencode_tools,
            mcp_ids,
            now,
            now,
        )
        async with db.execute(sql, params) as cur:
            # SQLite: get last inserted rowid, then fetch the row by rowid
            rowid = cur.lastrowid

        # Retrieve the created row (id is generated by DEFAULT expression)
        async with db.execute("SELECT * FROM skills WHERE rowid = ?", (rowid,)) as cur:
            row = await cur.fetchone()
        await db.commit()

        return self._strip_tools(self._row_to_dict(row))

    # ---- update ----

    async def update_skill(
        self, db: aiosqlite.Connection, skill_id: str, data: dict
    ) -> dict | None:
        """更新技能"""
        existing = await self._get_raw(db, skill_id)
        if existing is None:
            return None

        updatable_fields = {
            "name",
            "description",
            "category",
            "complexity",
            "recommended_model_tier",
            "applicable_positions",
            "applicable_min_level",
            "is_active",
            "instructions",
            "opencode_tools",
            "mcp_ids",
        }

        sets: list[str] = []
        params: list[object] = []
        for key, value in data.items():
            if key not in updatable_fields:
                continue
            if key == "applicable_positions" and isinstance(value, list):
                value = json.dumps(value)
            if key in ("opencode_tools", "mcp_ids") and isinstance(value, list):
                value = json.dumps(value)
            sets.append(f"{key} = ?")
            params.append(value)

        if not sets:
            return self._strip_tools(dict(existing))

        sets.append("version = version + 1")
        sets.append("updated_at = ?")
        params.append(datetime.now(timezone.utc).isoformat())
        params.append(skill_id)

        sql = f"UPDATE skills SET {', '.join(sets)} WHERE id = ?"
        await db.execute(sql, params)
        await db.commit()

        return await self.get_skill(db, skill_id)

    # ---- delete ----

    async def delete_skill(self, db: aiosqlite.Connection, skill_id: str) -> bool:
        """删除技能。预置技能不可删除。"""
        existing = await self._get_raw(db, skill_id)
        if existing is None:
            return False
        if existing["is_preset"]:
            raise ValueError("预置技能不可删除")

        async with db.execute(
            "SELECT COUNT(*) FROM persona_skills WHERE skill_id = ?", (skill_id,)
        ) as cur:
            row = await cur.fetchone()
            ref_count = row[0] if row else 0
        if ref_count > 0:
            raise ValueError(f"该技能已被 {ref_count} 个员工绑定，请先解绑后再删除")

        async with db.execute(
            "SELECT COUNT(*) FROM wf_nodes WHERE skill_id = ?", (skill_id,)
        ) as cur:
            row = await cur.fetchone()
            wf_count = row[0] if row else 0
        if wf_count > 0:
            raise ValueError(f"该技能已被 {wf_count} 个工作流节点使用，请先移除后再删除")

        await db.execute("DELETE FROM skills WHERE id = ?", (skill_id,))
        await db.commit()
        return True

    # ---- 岗位+等级匹配 ----

    async def get_skills_for_position(
        self, db: aiosqlite.Connection, position_id: str, level: str
    ) -> dict:
        """根据岗位+等级获取可用技能（分推荐/可选/不可选三档）

        - 推荐: applicable_positions 包含该岗位 AND 用户等级 >= 技能最低等级
        - 可选: 不在推荐中但用户等级 >= 技能最低等级
        - 不可选(locked): 用户等级不够
        """
        level_map = {"junior": 1, "mid": 2, "senior": 3, "expert": 4}
        complexity_level = {"basic": 1, "medium": 2, "complex": 3, "special": 4}  # noqa: F841

        all_skills = await self.list_skills(db, is_active=True)
        user_level = level_map.get(level, 1)

        recommended: list[dict] = []
        optional: list[dict] = []
        locked: list[dict] = []

        for skill in all_skills:
            min_level_required = level_map.get(
                skill.get("applicable_min_level", "junior"), 1
            )
            applicable = json.loads(skill.get("applicable_positions") or "[]")

            if user_level < min_level_required:
                locked.append(skill)
            elif position_id in applicable:
                recommended.append(skill)
            else:
                optional.append(skill)

        return {
            "recommended": recommended,
            "optional": optional,
            "locked": locked,
        }

    # ---- export ----

    async def export_as_skillmd(self, db: aiosqlite.Connection, skill_id: str) -> str | None:
        """导出技能为 SKILL.md 格式"""
        import yaml as _yaml
        raw = await self._get_raw(db, skill_id)
        if raw is None:
            return None

        frontmatter: dict = {"name": raw["name"]}
        if raw.get("description"):
            frontmatter["description"] = raw["description"]
        frontmatter["category"] = raw["category"]
        frontmatter["complexity"] = raw["complexity"]
        frontmatter["recommended-model-tier"] = raw["recommended_model_tier"]
        if raw.get("opencode_tools"):
            frontmatter["allowed-tools"] = json.loads(raw["opencode_tools"])
        if raw.get("mcp_ids"):
            mcp_ids = json.loads(raw["mcp_ids"])
            if mcp_ids:
                # 查询 MCP 连接名称（导出用名称而非 ID）
                names: list[str] = []
                for mcp_id in mcp_ids:
                    async with db.execute(
                        "SELECT name FROM mcp_connections WHERE id = ?", (mcp_id,)
                    ) as cur:
                        mcp_row = await cur.fetchone()
                    names.append(mcp_row[0] if mcp_row else mcp_id)
                frontmatter["mcp-connections"] = names
        if raw.get("applicable_min_level") and raw["applicable_min_level"] != "junior":
            frontmatter["min-level"] = raw["applicable_min_level"]

        lines = ["---"]
        lines.append(_yaml.dump(frontmatter, allow_unicode=True, default_flow_style=False).strip())
        lines.append("---")
        lines.append("")
        if raw.get("instructions"):
            lines.append(raw["instructions"])

        return "\n".join(lines)

    # ---- internal ----

    async def _get_raw(self, db: aiosqlite.Connection, skill_id: str) -> dict | None:
        """Get raw row (including tools_json) for internal use."""
        async with db.execute("SELECT * FROM skills WHERE id = ?", (skill_id,)) as cur:
            row = await cur.fetchone()
        return self._row_to_dict(row) if row else None


skill_service = SkillService()
